### ISSUE TITLE
Not working fully on GS 3.38

### ISSUE THREAD

**Issue by fawtytoo** [mipmip/gnome-shell-extensions-hotkeys-popup#1]
Although you don't support it, this works in 3.38 apart from the preferences. Any chance of making it work?

Technical details:
`TypeError: GObject.ParamSpec.jsobject is not a function

Stack trace:
  @/home/steve/.local/share/gnome-shell/extensions/hotkeys-popup@pimsnel.com/ui.js:12:35
  @/home/steve/.local/share/gnome-shell/extensions/hotkeys-popup@pimsnel.com/prefs.js:27:12
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17`
